// REVOY25_PRESETS — 46 Deevad 25.01 brush presets (David Revoy, Jan 2025)
// Auto-generated by tools/kpp2preset.py
// License: CC-0

;(function(app) {

    const REVOY25_PRESETS = {

        /* eraser_eraser-tip */
        'eraser_eraser-tip': {
            _eraserMode: true,
            startSize: 100,
            endSize: 80,
            spacing: 5,
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/chalk_chisel_losange_202210A.gih",
            _tipUrlPng: "brush-packs/revoy-2025/tips/chalk_chisel_losange_202210A.png",
            _nativeShape: "circle",
            _opacityLUT: [[0.0, 0.0], [0.751256, 1.0]],
            _flowLUT: [[0.0, 0.0], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.500252], [1.0, 1.0]],
            taper: 10,
            scatter: 1,
            scatterRadius: 14,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* eraser_eraser-kneaded-soft */
        'eraser_eraser-kneaded-soft': {
            startSize: 200,
            endSize: 200,
            spacing: 10,
            _opacityLUT: [[0.0, 0.0], [0.190955, 0.110553], [0.769853, 1.0]],
            _flowLUT: [[0.0, 0.0], [0.169082, 0.306533], [0.270531, 1.0]],
            _sizeLUT: [[0.0, 0.487437], [1.0, 1.0]],
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* basic_airbrush */
        'basic_airbrush': {
            startSize: 200,
            endSize: 200,
            spacing: 10,
            _opacityLUT: [[0.0, 0.0], [0.502008, 0.321285], [1.0, 1.0]],
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* basic_basic-size-fill-area */
        'basic_basic-size-fill-area': {
            startSize: 32,
            endSize: 26,
            spacing: 10,
            _sizeLUT: [[0.0, 0.0], [0.084577, 0.030151], [0.487562, 0.457286], [0.915423, 1.0]],
            taper: 9,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* basic_basic-oval-brush */
        'basic_basic-oval-brush': {
            startSize: 40,
            endSize: 32,
            spacing: 2,
            angle: 6,
            _opacityLUT: [[0.0, 0.0], [1.0, 1.0]],
            _flowLUT: [[0.0, 0.0], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.24498], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* basic_basic-size-pressure */
        'basic_basic-size-pressure': {
            startSize: 20,
            endSize: 16,
            spacing: 6,
            _opacityLUT: [[0.0, 0.0], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.039719], [1.0, 1.0]],
            taper: 10,
            scatter: 1,
            scatterRadius: 3,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* basic_thin-basic-details */
        'basic_thin-basic-details': {
            startSize: 12,
            endSize: 9,
            _opacityLUT: [[0.0, 0.0], [0.21005, 0.0401], [0.594975, 0.185427], [0.7799, 0.390453], [1.0, 1.0]],
            _flowLUT: [[0.0, 0.0], [0.246231, 0.18593], [0.341709, 0.437186], [0.496231, 1.0]],
            _sizeLUT: [[0.0, 0.245703], [1.0, 1.0]],
            taper: 12,
            scatter: 1,
            scatterRadius: 2,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* pencil_pencil-h-sketch */
        'pencil_pencil-h-sketch': {
            endSize: 6,
            _opacityLUT: [[0.0, 0.0], [1.0, 1.0]],
            flow: 40,
            _flowLUT: [[0.0, 0.0], [1.0, 0.773869]],
            taper: 12,
            scatter: 1,
            scatterRadius: 1,
            _scatterLUT: [[0.0, 1.0], [1.0, 0.113537]],
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* pencil_mechanical-pencil-detail */
        'pencil_mechanical-pencil-detail': {
            startSize: 100,
            endSize: 80,
            spacing: 2,
            _opacityLUT: [[0.0, 0.331658], [1.0, 1.0]],
            _flowLUT: [[0.0, 0.482412], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.301508], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* pencil_pencil-2b */
        'pencil_pencil-2b': {
            startSize: 12,
            endSize: 10,
            angle: 5,
            _opacityLUT: [[0.0, 0.0], [0.060302, 0.206031], [0.366834, 0.733669], [1.0, 1.0]],
            _flowLUT: [[0.0, 0.0], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.37219], [1.0, 1.0]],
            taper: 8,
            scatter: 1,
            scatterRadius: 2,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* pencil_thin-brush-textured */
        'pencil_thin-brush-textured': {
            startSize: 11,
            endSize: 9,
            _opacityLUT: [[0.0, 0.422111], [0.347032, 0.552764], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.485944], [1.0, 1.0]],
            taper: 9,
            scatter: 14,
            scatterRadius: 16,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* pencil_bristles-lineart */
        'pencil_bristles-lineart': {
            startSize: 100,
            endSize: 80,
            spacing: 4,
            _opacityLUT: [[0.0, 0.0], [0.067358, 0.039301], [0.754237, 1.0]],
            flow: 40,
            _sizeLUT: [[0.0, 0.634834], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* pencil_thin-brush-regular */
        'pencil_thin-brush-regular': {
            startSize: 100,
            endSize: 80,
            spacing: 2,
            angle: 3,
            _opacityLUT: [[0.0, 0.331658], [0.5, 1.0]],
            _sizeLUT: [[0.0, 0.100402], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* pencil_thin-brush-hard-edge-textured */
        'pencil_thin-brush-hard-edge-textured': {
            startSize: 100,
            endSize: 80,
            spacing: 7,
            hardness: 0,
            _sizeLUT: [[0.0, 0.0], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: false, v: true}
        }
,

        /* pencil_thin-brush-pointy */
        'pencil_thin-brush-pointy': {
            startSize: 100,
            endSize: 80,
            spacing: 4,
            flow: 40,
            _sizeLUT: [[0.0, 0.1], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* block_block-brush-glazing */
        'block_block-brush-glazing': {
            startSize: 100,
            endSize: 80,
            spacing: 30,
            _spacingLUT: [[0.0, 1.0], [0.128079, 0.660099], [0.334975, 0.359606], [1.0, 0.054187]],
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/rock_pitted-fixed.gih",
            _tipUrlPng: "brush-packs/revoy-2025/tips/rock_pitted-fixed.png",
            _nativeShape: "circle",
            _opacityLUT: [[0.0, 0.0], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.5], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* block_bristle-flat-glazing */
        'block_bristle-flat-glazing': {
            startSize: 100,
            endSize: 80,
            spacing: 2,
            angle: 3,
            _opacityLUT: [[0.0, 0.0], [0.25, 0.13], [0.75502, 1.0]],
            _sizeLUT: [[0.0, 0.0], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* block_charcoal-rock-soft */
        'block_charcoal-rock-soft': {
            startSize: 100,
            endSize: 80,
            spacing: 12,
            angle: 2,
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/chalk_chisel_random_small.gih",
            _tipUrlPng: "brush-packs/revoy-2025/tips/chalk_chisel_random_small.png",
            _nativeShape: "circle",
            _opacityLUT: [[0.0, 0.0], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.783133], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: true, v: true}
        }
,

        /* block_glazing-round */
        'block_glazing-round': {
            startSize: 100,
            endSize: 80,
            spacing: 6,
            _opacityLUT: [[0.0, 0.0], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.35], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* block_glazing-textured */
        'block_glazing-textured': {
            startSize: 100,
            endSize: 80,
            spacing: 10,
            _spacingLUT: [[0.0, 1.0], [0.128079, 0.660099], [0.334975, 0.359606], [1.0, 0.054187]],
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/deevad-202210C_compact-fix.gih",
            _tipUrlPng: "brush-packs/revoy-2025/tips/deevad-202210C_compact-fix.png",
            _nativeShape: "circle",
            _opacityLUT: [[0.0, 0.0], [1.0, 1.0]],
            _flowLUT: [[0.0, 0.095477], [0.713179, 0.336643], [0.807692, 0.462312], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.485593], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* block_shape-blocker-textured */
        'block_shape-blocker-textured': {
            startSize: 100,
            endSize: 80,
            spacing: 30,
            _spacingLUT: [[0.0, 1.0], [0.128079, 0.660099], [0.334975, 0.359606], [1.0, 0.054187]],
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/rock_pitted-fixed-B.gih",
            _tipUrlPng: "brush-packs/revoy-2025/tips/rock_pitted-fixed-B.png",
            _nativeShape: "circle",
            _opacityLUT: [[0.0, 0.0], [0.246231, 0.201005], [0.767068, 1.0]],
            _sizeLUT: [[0.0, 0.485593], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* bristle_bristle-thick-textured */
        'bristle_bristle-thick-textured': {
            startSize: 100,
            endSize: 80,
            spacing: 21,
            _spacingLUT: [[0.0, 1.0], [0.495192, 0.693468], [0.721154, 0.286432], [1.0, 0.080402]],
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/scratches_rough.gih",
            _tipUrlPng: "brush-packs/revoy-2025/tips/scratches_rough.png",
            _nativeShape: "circle",
            _opacityLUT: [[0.0, 0.0], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.5], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* bristle_bristle-tilt-modeling */
        'bristle_bristle-tilt-modeling': {
            startSize: 100,
            endSize: 80,
            spacing: 3,
            angle: 2,
            _sizeLUT: [[0.0, 0.58952], [0.271948, 0.624454], [0.614333, 0.90393], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: true, v: false}
        }
,

        /* bristle_bristles-filler */
        'bristle_bristles-filler': {
            startSize: 100,
            endSize: 80,
            spacing: 2,
            angle: 2,
            _sizeLUT: [[0.0, 0.170854], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* bristle_hard-edge-textured-block */
        'bristle_hard-edge-textured-block': {
            startSize: 100,
            endSize: 80,
            spacing: 6,
            angle: 2,
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/deevad-202210C_compact-fix.gih",
            _tipUrlPng: "brush-packs/revoy-2025/tips/deevad-202210C_compact-fix.png",
            _nativeShape: "circle",
            _flowLUT: [[0.0, 0.0], [0.514056, 1.0]],
            hardness: 0,
            _sizeLUT: [[0.0, 0.0], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: true, v: false}
        }
,

        /* bristle_rough-rake-textured */
        'bristle_rough-rake-textured': {
            startSize: 100,
            endSize: 80,
            spacing: 2,
            _opacityLUT: [[0.0, 0.0], [1.0, 1.0]],
            _flowLUT: [[0.0, 0.482412], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.0], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* bristle_textured-crease-update */
        'bristle_textured-crease-update': {
            startSize: 100,
            endSize: 80,
            spacing: 5,
            _flowLUT: [[0.0, 0.0], [0.62249, 0.257028], [0.754151, 0.421788], [1.0, 1.0]],
            hardness: 0,
            _sizeLUT: [[0.0, 0.316583], [0.257028, 0.401606], [0.626506, 0.779116], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: false, v: true}
        }
,

        /* bristle_thick-dry-canvas */
        'bristle_thick-dry-canvas': {
            startSize: 100,
            endSize: 80,
            spacing: 10,
            _opacityLUT: [[0.0, 0.0], [0.5, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* water_water-edges */
        'water_water-edges': {
            startSize: 100,
            endSize: 80,
            spacing: 2,
            angle: 2,
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/chalk_chisel_random.gih",
            _tipUrlPng: "brush-packs/revoy-2025/tips/chalk_chisel_random.png",
            _nativeShape: "circle",
            opacity: 70,
            _opacityLUT: [[0.0, 1.0], [1.0, 1.0]],
            _flowLUT: [[0.0, 0.351759], [0.22549, 0.386935], [0.764706, 1.0]],
            _sizeLUT: [[0.0, 0.0], [0.1, 0.05], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 100,
            grainScale: 3,
            _mirror: {h: false, v: true}
        }
,

        /* Wet Modeling */
        'water_wet-modeling': {
            _paintopid: "colorsmudge",
            _unsupported: true
        }
,

        /* Glazing Round Mix */
        'mix_glazing-round-mix': {
            _paintopid: "colorsmudge",
            _unsupported: true
        }
,

        /* Blender Rake Smudge */
        'blender_blender-rake-smudge': {
            _paintopid: "colorsmudge",
            _unsupported: true
        }
,

        /* Blender Textured Soft */
        'blender_blender-textured-soft': {
            _paintopid: "colorsmudge",
            _unsupported: true
        }
,

        /* Blender Wet Area */
        'blender_blender-wet-area': {
            _paintopid: "colorsmudge",
            _unsupported: true
        }
,

        /* Shapes Alchemy */
        'shapes_shapes-alchemy': {
            _paintopid: "experimentbrush",
            _unsupported: true
        }
,

        /* Distort Move Update */
        'distort_distort-move-update': {
            _paintopid: "deformbrush",
            _unsupported: true
        }
,

        /* chaotic_textured-chaotic-irregular */
        'chaotic_textured-chaotic-irregular': {
            startSize: 100,
            endSize: 80,
            spacing: 40,
            _spacingLUT: [[0.0, 0.570281], [0.148159, 0.4352], [0.443409, 0.24314], [1.0, 0.054187]],
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/random-debris.gbr",
            _tipUrlPng: "brush-packs/revoy-2025/tips/random-debris.png",
            _nativeShape: "circle",
            _opacityLUT: [[0.0, 0.0], [0.497721, 1.0]],
            _sizeLUT: [[0.0, 0.5], [1.0, 1.0]],
            taper: 10,
            scatterRadius: 4,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* texture_canvas-rub-texture */
        'texture_canvas-rub-texture': {
            startSize: 100,
            endSize: 80,
            spacing: 3,
            _flowLUT: [[0.0, 0.0], [1.0, 1.0]],
            _sizeLUT: [[0.0, 0.58952], [0.271948, 0.624454], [0.614333, 0.90393], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: true, v: false}
        }
,

        /* texture_dry-scratch-texture */
        'texture_dry-scratch-texture': {
            startSize: 100,
            endSize: 80,
            spacing: 16,
            angle: 2,
            _sizeLUT: [[0.0, 0.58952], [0.271948, 0.624454], [0.614333, 0.90393], [1.0, 1.0]],
            taper: 10,
            scatter: 1,
            scatterRadius: 11,
            _scatterLUT: [[0.0, 0.0], [1.0, 1.0]],
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: true, v: false}
        }
,

        /* texture_splatters-large */
        'texture_splatters-large': {
            startSize: 100,
            endSize: 80,
            spacing: 5,
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/splats_large.gih",
            _tipUrlPng: "brush-packs/revoy-2025/tips/splats_large.png",
            _nativeShape: "circle",
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: true, v: true}
        }
,

        /* texture_splatters-light */
        'texture_splatters-light': {
            startSize: 100,
            endSize: 80,
            spacing: 33,
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* texture_squiggles */
        'texture_squiggles': {
            startSize: 100,
            endSize: 80,
            spacing: 25,
            _opacityLUT: [[0.0, 0.0], [0.25, 0.1], [0.75, 0.9], [1.0, 1.0]],
            taper: 10,
            scatter: 2,
            scatterRadius: 26,
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: true, v: true}
        }
,

        /* texture_texture-feeding-canvas */
        'texture_texture-feeding-canvas': {
            startSize: 100,
            endSize: 80,
            spacing: 10,
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/impressionism_brush.gih",
            _tipUrlPng: "brush-packs/revoy-2025/tips/impressionism_brush.png",
            _nativeShape: "circle",
            _sizeLUT: [[0.0, 0.436308], [0.323671, 0.497487], [1.0, 1.0]],
            taper: 10,
            scatter: 8,
            scatterRadius: 50,
            _scatterLUT: [[0.0, 0.0], [1.0, 1.0]],
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: true, v: true}
        }
,

        /* texture_textured-big-sponge */
        'texture_textured-big-sponge': {
            startSize: 100,
            endSize: 80,
            spacing: 25,
            _sizeLUT: [[0.0, 0.783133], [1.0, 1.0]],
            taper: 10,
            scatter: 14,
            scatterRadius: 50,
            airbrushRate: 20,
            grainScale: 3
        }
,

        /* texture_textured-random-noise */
        'texture_textured-random-noise': {
            startSize: 100,
            endSize: 80,
            spacing: 25,
            taper: 10,
            scatter: 2,
            scatterRadius: 26,
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: true, v: true}
        }
,

        /* texture_foliage */
        'texture_foliage': {
            startSize: 100,
            endSize: 80,
            spacing: 3,
            shape: "custom",
            _tipUrl: "brush-packs/revoy-2025/tips/vegetal_stylised.gih",
            _tipUrlPng: "brush-packs/revoy-2025/tips/vegetal_stylised.png",
            _nativeShape: "circle",
            _opacityLUT: [[0.0, 0.0], [0.25, 0.1], [0.75, 0.9], [1.0, 1.0]],
            taper: 10,
            scatter: 2,
            scatterRadius: 26,
            airbrushRate: 20,
            grainScale: 3,
            _mirror: {h: true, v: true}
        }

    };

    /* Register into PRESETS via app._PRESETS */
    var PRESETS = app._PRESETS;
    if (PRESETS) {
        Object.keys(REVOY25_PRESETS).forEach(function(key) {
            PRESETS['revoy25:' + key] = REVOY25_PRESETS[key];
        });
    }

    /* Expose public API */
    app._REVOY25_PRESETS = REVOY25_PRESETS;

    if (app.brush) {
        app.brush.listRevoy25Presets = function() {
            return Object.keys(REVOY25_PRESETS);
        };

        app.brush.loadRevoy25Preset = function(name) {
            var key = 'revoy25:' + name;
            if (!PRESETS || !PRESETS[key]) {
                var lower = name.toLowerCase();
                var found = Object.keys(REVOY25_PRESETS).find(function(k) {
                    return k.toLowerCase().indexOf(lower) !== -1;
                });
                if (found) key = "revoy25:" + found;
                else { console.warn('[Revoy25] Unknown preset:', name); return false; }
            }
            app.brush.loadPreset(key);
            return true;
        };
    }

})(PaintApp);
